# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the app for production
# RUN npm run build

# Expose the port the app will run on
EXPOSE 5173

# Command to run the app
CMD ["npm", "run", "dev"] 